### PR TITLE
Snow 277233 move out  Bintray from release pipeline 

### PR DESCRIPTION
**Pull request by sfc-gh-abhatnagar**

### CODE REVIEW

**Comment by sfc-gh-mrui** [comment]
Please refer to https://github.com/snowflakedb/spark-snowflake/pull/349 to see what files need to update for new spark connector versionn.

**Comment by sfc-gh-abhatnagar** [comment]
> Please refer to #349 to see what files need to update for new spark connector versionn.

I have updated the files as per that PR

**Review by sfc-gh-mrui — APPROVED** [review]
LGTM

**Comment by sfc-gh-abhatnagar** [comment]
@binglihub can you please review this as well , as repo needs 2 approvers

**Review by sfc-gh-bli — APPROVED** [review]
LGTM

**Pull request merged**
