### PR TITLE
support spark 3.5

### LINKED ISSUE #533: [Request] Support Spark 3.5
Hello,

Is it plan for a support of new release of spark 3.5 ? 

Thanks

### PR DESCRIPTION
**Pull request by parthshyara**
* Support `Spark 3.5`. Fixes #533.
* Upgrade JDBC version to `3.15.0`

### CODE REVIEW

**Comment by parthshyara** [comment]
@sfc-gh-bli @sfc-gh-jdu Kindly update if there are any timelines for this.

**Comment by parthshyara** [comment]
@sfc-gh-bli @sfc-gh-jdu @sfc-gh-ema Kind reminder asking for the update on the timelines.

**Comment by sfc-gh-bli** [comment]
@parthshyara
Thank you for your contribution. We will not merge this PR since it has many issues. We are working on a new Spark connector release `3.0.0`, which will compatible with Spark 3.5.
This connector `3.0.0` will be released by the end of July.

**Comment by parthshyara** [comment]
Great! Thank you for responding. Closing this PR.

**Comment by kraj007** [comment]
> @parthshyara Thank you for your contribution. We will not merge this PR since it has many issues. We are working on a new Spark connector release `3.0.0`, which will compatible with Spark 3.5. This connector `3.0.0` will be released by the end of July.

@sfc-gh-bli  Is this plan on track? Can we expect connector version by July month end ? Please confirm , we are eagerly waiting for this ask.

**Comment by kraj007** [comment]
> @kraj007 yes, we are working on it.

Appreciate your response @sfc-gh-bli ! Regarding java version compatibility, does it support java 17 version ?

**Pull request closed without merging**
