### PR TITLE
PRODSEC-880 new semgrep integration

### PR DESCRIPTION
**Pull request by sfc-gh-spandey**

### CODE REVIEW

**Comment by sfc-gh-bli** [comment]
@sfc-gh-spandey What is it for?

**Comment by sfc-gh-spandey** [comment]
Hi @sfc-gh-bli this is for adding semgrep static analysis check to new PRs in this repo
We're using semgrep to detect code issues

You can find more info on the wiki page https://snowflakecomputing.atlassian.net/wiki/spaces/CLO/pages/1127055936/Semgrep+Handbook

**Review by sfc-gh-bli — APPROVED** [review]
LGTM

**Review by sfc-gh-ema — APPROVED** [review]

**Comment by sfc-gh-spandey** [comment]
hi folks, could one of you please merge this PR? I don't have permissions for it
thank you!

**Comment by sfc-gh-mrui** [comment]
> hi folks, could one of you please merge this PR? I don't have permissions for it
> thank you!

Hi, @sfc-gh-spandey,
Any guide to run the tool local to check existing code before merging the github action?

**Comment by sfc-gh-spandey** [comment]
Hi @sfc-gh-mrui we'll be running the tool against existing code in the repository in the future once we've ensured the ruleset is stable in github actions

We'll create jira tickets for any issues found in the existing code in the repository and have the semgrep check be changed to required status check at that point

**Pull request merged**
